version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/plugins/sms-kit"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
